# Generated by Django 6.0.7 on 2026-07-19 19:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('video_id', models.CharField(max_length=11)),
                ('title', models.TextField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_watched', models.BooleanField(default=False)),
                ('liked', models.BooleanField(default=False)),
                ('bookmarked', models.BooleanField(default=False)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('curator', models.CharField(default='@feed_master', max_length=100)),
                ('category', models.CharField(default='Tech', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
