# Generated by Django 6.0.7 on 2026-07-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='is_watched',
            new_name='is_clean',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='author_name',
            new_name='source_name',
        ),
        migrations.AddField(
            model_name='link',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('code', 'Code Repository'), ('general', 'General Link')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='link',
            name='video_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
