# Generated by Django 6.0.7 on 2026-08-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_rename_is_watched_link_is_clean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
