# Generated by Django 6.0.7 on 2026-09-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_link_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='watched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
